[variables]
main_domain = "${domain}"
postgres_user = "${username}"
postgres_password = "${password:24}"
postgres_db = "n8n"
n8n_encryption_key = "${base64:64}"
n8n_runner_secret = "${base64:64}"

[config]
mounts = []

[[config.domains]]
serviceName = "n8n"
port = 5_678
host = "${main_domain}"

[config.env]
N8N_HOST = "${main_domain}"
N8N_PORT = "5678"
N8N_RUNNERS_SECRET = "${n8n_runner_secret}"

PROXY_HOPS = "0"
ENCRYPTION_KEY = "${n8n_encryption_key}"
GENERIC_TIMEZONE = "Europe/Berlin"

POSTGRES_DB = "${postgres_db}"
POSTGRES_USER = "${postgres_user}"
POSTGRES_PASSWORD = "${postgres_password}"

OLLAMA_HOST = "http://ollama:11434"

SMTP_HOST = ""
SMTP_PORT = "587"
SMTP_USER = ""
SMTP_PASS = ""