version: "3.8"
services:
  komari:
    image: ghcr.io/komari-monitor/komari:latest
    restart: unless-stopped
    volumes:
      - komari-data:/app/data
    environment:
      - ADMIN_USERNAME
      - ADMIN_PASSWORD

volumes:
  komari-data: {}
